aws_region: ap-northeast-1
aws_keypair: bbrfkr-keypair-for-aws
aws_ami_id: ami-6be57d0d
aws_instances:
- tags:
    Name: bbrfkr-instance-iac-test
    Env: iac
  instance_type: t2.micro
  security_group: bbrfkr-sg-web
  state: present
  vpc_subnet: bbrfkr-subnet-iac
  az: ap-northeast-1c
  assign_public_ip: yes
