---
- name: configure service
  hosts: "{{ target }}"
  remote_user: ec2-user
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    become: yes
  - name: put index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
    become: yes
  - name: enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
    become: yes

