---
- name: deploy test environment
  hosts: "{{ target }}"
  gather_facts: no
  vars_files:
  - vars/vars.yaml
  tasks:
  - name: get record sets
    route53_facts:
      hosted_zone_id: "{{ aws_hosted_zone_id }}"
      query: record_sets
    register: reg_record_sets
  - name: set var for test ip
    set_fact:
      test_ip: "{{ item.ResourceRecords.0.Value }}"
    when: item.Name == "test.bbrfkr.tk."
    with_items: "{{ reg_record_sets.ResourceRecordSets }}"
  - name: check instance id of test instance
    ec2_instance_facts:
      region: "{{ aws_region }}"
      filters:
        instance-state-name: running
        "tag:Name": "bbrfkr-instance-test-{{ ec2_tag_Color }}"
    register: reg_test_instance
  - name: associate eip to test instance
    ec2_eip:
      region: "{{ aws_region }}"
      device_id: "{{ reg_test_instance.instances.0.instance_id }}"
      public_ip: "{{ test_ip }}"
    when: reg_iac_jenkins.instances != []
