---
- name: unit test
  hosts: "{{ target }}"
  gather_facts: no
  vars_files:
  - vars/vars.yaml
  tasks:
  - name: get content by curl
    shell: curl http://{{ ec2_ip_address }}
    changed_when: false
    delegate_to: localhost
    register: reg_curl_test
  - name: curl test
    assert:
      that:
      - "'app version: {{ version }}' in reg_curl_test.stdout"
    delegate_to: localhost
