---
- name: configure service
  hosts: "{{ target }}"
  gather_fact: no
  tasks:
  - name: get content by curl
    shell: curl http://{{ ansible_host }}
    delegate_to: localhost
    register: reg_curl_test
  - name: curl test
    assert:
      that:
      - "'env: iac' in reg_curl_test.stdout"
    delegate_to: localhost
